Fix linker script and get IO to fit flash
PX4/PX4-Bootloader pull request #197
Opened 2021-05-01 12:36 UTC by julianoes

This includes the fixes to the linker scripts that you suggested as well as some flash saving to make IO fit.

Best reviewed commit by commit.

2021-05-01 13:27 UTC, LorenzMeier approved these changes

2021-05-01 13:38 UTC, davids5 requested changes

2021-05-01 13:38 UTC, davids5 commented on bl.c
> +#ifndef DISABLE_FOR_IO
I think we want to garbage collect. If we need to disable weith #define use a feature like NO_CIN_WORD and not the HW name, That way HW can share it as a feature.

2021-05-03 15:16 UTC, davids5 approved these changes

2021-05-03 15:16 UTC, merged