Replace travis-ci with GitHub actions
PX4/PX4-Bootloader pull request #198
Opened 2021-05-01 12:55 UTC by julianoes

I'm not sure if the deploy stuff is still used and have ignored it.

2021-05-01 12:55 UTC, TSC21 approved these changes

2021-05-01 13:02 UTC, davids5 requested changes

2021-05-01 13:02 UTC, davids5 commented on .github/workflows/main.yaml
> +            tar -jxf gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
wget file not the un-tar-ed one

2021-05-01 14:40 UTC, dagar commented
Build failing.

Once this is working it can be updated to store the artifacts and then the Jenkinsfile can be deleted.

2021-05-02 16:51 UTC, julianoes commented
> Build failing.

I can see that :smile:.

```
Makefile:69: Your toolchain doesn't support -mcpu=cortex-m7.
Please use gcc-arm-embedded 4.8 2014q3 or newer. Skipping this sub-library.
```

That's with arm-none-eabi-gcc 9.3.1. We would need this one: https://github.com/libopencm3/libopencm3/commit/cccc1267c5d14105aec94e0606d184a2f2dd2008

2021-05-03 12:49 UTC, davids5 requested changes
Depends on https://github.com/PX4/PX4-Bootloader/pull/197 coming in first. So the code for the IO fits with GCC 9

2021-05-03 13:59 UTC, julianoes commented
I've tested this together with #197:

> px4fmu-v2: flashing 2x worked, -b works, flashing IO worked 3x,
px4fmu-v4: flashing 2x worked, -b works
px4fmu-v5: flashing FMU 2x worked, -b works, flashing IO 3x

2021-05-03 15:17 UTC, davids5 approved these changes

2021-05-03 15:17 UTC, merged